---
# role: ansible-role-timesyncd
# file: tasks/tasks.yml

- name: "Remove ntp packages"
  package:
    name: "{{ timesyncd_remove_packages }}"
    state: absent

- name: "Run timedatectl status"
  command: "{{ timesyncd_timedatectl | quote }} status"
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: "Write timesyncd.conf"
  template:
    src: "etc/systemd/timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart and enable systemd-timesyncd

- name: "Set timezone"
  command: "sudo timedatectl set-timezone {{ timesyncd_timezone | quote }}"
  when: timesyncd_timezone not in timedatectl_result.stdout

- name: "Enable ntp"
  command: "{{ timesyncd_timedatectl | quote }} set-ntp 1"
  when: "'Network time on: no' in timedatectl_result.stdout"
